# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(649, 480)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        Dialog.setFont(font)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 430, 621, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(140, 120, 391, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(170, 180, 64, 31))
        self.label_2.setObjectName("label_2")
        self.stuID = QtWidgets.QLineEdit(Dialog)
        self.stuID.setGeometry(QtCore.QRect(250, 180, 221, 31))
        self.stuID.setObjectName("stuID")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(170, 220, 64, 31))
        self.label_3.setObjectName("label_3")
        self.stuCode = QtWidgets.QLineEdit(Dialog)
        self.stuCode.setGeometry(QtCore.QRect(250, 220, 221, 31))
        self.stuCode.setEchoMode(QtWidgets.QLineEdit.Password)
        self.stuCode.setObjectName("stuCode")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(40, 280, 571, 121))
        self.label_4.setObjectName("label_4")
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QtCore.QRect(20, 430, 391, 31))
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", -1)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(100, 20, 460, 90))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/images/TAGS.png"))
        self.label_5.setObjectName("label_5")
        self.showPassword = QtWidgets.QPushButton(Dialog)
        self.showPassword.setGeometry(QtCore.QRect(480, 220, 51, 32))
        self.showPassword.setObjectName("showPassword")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">登录到1系统</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">学号</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">密码</span></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">安全性声明</p><p align=\"center\">本程序仅会使用您的密码访问以下功能：成绩查询、信息查询、校历查询。</p><p align=\"center\">您的密码不会被记录或发送到任何服务器</p><p align=\"center\">您的明文密码将会在离开此对话框后即刻销毁</p></body></html>"))
        self.showPassword.setText(_translate("Dialog", "显示"))

