# Form implementation generated from reading ui file 'manualLogin.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(540, 171)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        Dialog.setFont(font)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(180, 130, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 30, 431, 21))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(20, 60, 501, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.cookieHelpLebel = QtWidgets.QLabel(Dialog)
        self.cookieHelpLebel.setGeometry(QtCore.QRect(160, 80, 361, 41))
        self.cookieHelpLebel.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.cookieHelpLebel.setOpenExternalLinks(True)
        self.cookieHelpLebel.setObjectName("cookieHelpLebel")
        self.cookieHelpLebel_5 = QtWidgets.QLabel(Dialog)
        self.cookieHelpLebel_5.setGeometry(QtCore.QRect(20, 80, 131, 41))
        self.cookieHelpLebel_5.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.cookieHelpLebel_5.setOpenExternalLinks(True)
        self.cookieHelpLebel_5.setObjectName("cookieHelpLebel_5")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "手动登陆至1系统"))
        self.label.setText(_translate("Dialog", "请在下方方框中输入手动获取的1系统cookie："))
        self.cookieHelpLebel.setText(_translate("Dialog", "<html><head/><body><p align=\"right\"><a href=\"https://blog.cinea.com.cn/TJAGS/howcookie.html\"><span style=\" text-decoration: underline; color:#0000ff;\">不知道如何获取cookie？点击这里查看超详细教程</span></a></p></body></html>"))
        self.cookieHelpLebel_5.setText(_translate("Dialog", "<html><head/><body><p><a href=\"https://1.tongji.edu.cn\"><span style=\" text-decoration: underline; color:#0000ff;\">一键前往1系统</span></a></p></body></html>"))
